[2024-12-05T12:31:02.674+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T12:31:02.700+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: article_summarization_dag.process_article manual__2024-12-05T12:30:50.581181+00:00 [queued]>
[2024-12-05T12:31:02.715+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: article_summarization_dag.process_article manual__2024-12-05T12:30:50.581181+00:00 [queued]>
[2024-12-05T12:31:02.716+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-12-05T12:31:02.734+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): process_article> on 2024-12-05 12:30:50.581181+00:00
[2024-12-05T12:31:02.754+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'article_summarization_dag', 'process_article', 'manual__2024-12-05T12:30:50.581181+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/text_summarizatin.py', '--cfg-path', '/tmp/tmppnaa7o7r']
[2024-12-05T12:31:02.756+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask process_article
[2024-12-05T12:31:02.760+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6145) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-05T12:31:02.761+0000] {standard_task_runner.py:72} INFO - Started process 6153 to run task
[2024-12-05T12:31:02.811+0000] {task_command.py:467} INFO - Running <TaskInstance: article_summarization_dag.process_article manual__2024-12-05T12:30:50.581181+00:00 [running]> on host 76b7591512d5
[2024-12-05T12:31:02.956+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='article_summarization_dag' AIRFLOW_CTX_TASK_ID='process_article' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T12:30:50.581181+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T12:30:50.581181+00:00'
[2024-12-05T12:31:02.958+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-05T12:31:02.958+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-05T12:31:02.958+0000] {logging_mixin.py:190} INFO - Current task name:process_article state:running start_date:2024-12-05 12:31:02.701243+00:00
[2024-12-05T12:31:02.959+0000] {logging_mixin.py:190} INFO - Dag name:article_summarization_dag and current dag run status:running
[2024-12-05T12:31:02.959+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T12:31:04.128+0000] {logging_mixin.py:190} INFO - Data saved to /opt/***/dags/original_text.txt
[2024-12-05T12:31:04.130+0000] {logging_mixin.py:190} INFO - Data saved to /opt/***/dags/summary_text.txt
[2024-12-05T12:31:04.131+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/text_summarizatin.py", line 118, in process_article_and_save
    combine_and_save_files("original_text.txt", "summary_text.txt", "combined_text.txt")
  File "/opt/airflow/dags/text_summarizatin.py", line 91, in combine_and_save_files
    with open(original_filename, 'r', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'original_text.txt'
[2024-12-05T12:31:04.151+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-05T12:31:04.151+0000] {logging_mixin.py:190} INFO - Task start:2024-12-05 12:31:02.701243+00:00 end:2024-12-05 12:31:04.150223+00:00 duration:1.44898
[2024-12-05T12:31:04.152+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_article> dag:<DAG: article_summarization_dag> dagrun:<DagRun article_summarization_dag @ 2024-12-05 12:30:50.581181+00:00: manual__2024-12-05T12:30:50.581181+00:00, state:running, queued_at: 2024-12-05 12:30:50.600157+00:00. externally triggered: True>
[2024-12-05T12:31:04.152+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'original_text.txt'
[2024-12-05T12:31:04.152+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=article_summarization_dag, task_id=process_article, run_id=manual__2024-12-05T12:30:50.581181+00:00, execution_date=20241205T123050, start_date=20241205T123102, end_date=20241205T123104
[2024-12-05T12:31:04.174+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T12:31:04.176+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task process_article ([Errno 2] No such file or directory: 'original_text.txt'; 6153)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/text_summarizatin.py", line 118, in process_article_and_save
    combine_and_save_files("original_text.txt", "summary_text.txt", "combined_text.txt")
  File "/opt/airflow/dags/text_summarizatin.py", line 91, in combine_and_save_files
    with open(original_filename, 'r', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'original_text.txt'
[2024-12-05T12:31:04.223+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-05T12:31:04.251+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T12:31:04.253+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
